### ISSUE TITLE
should_receive cause mutable string error

### ISSUE THREAD

**Issue by fkchang** [opal/opal-rspec#12]
I get this
```
NotImplementedError:
       #<< not supported. Mutable String methods are not supported in Opal.
```
when using should_receive and any_instance.  Switching allow/expec(blah).to receive works though for should_receive

**Comment by rpierreye** [comment]
I agree... get same error for ```any_instance```

**Comment by wied03** [comment]
@rpierreye @fkchang - Check out the 0.5.0 beta, this should be addressed there already (but I added specs in PR 34 to ensure it works).
