### ISSUE TITLE
Add option to rake task for --backtrace

### ISSUE THREAD

**Issue by bk2204** [opal/opal-rspec#14]
Due to the nature of [my program](https://github.com/bk2204/daniel-ruby), I end up using a lot of pack and unpack calls, which I have to provide polyfills for, and native JavaScript.  Therefore, I end up getting a lot of exceptions because my polyfills are broken (or more likely, they use features Opal doesn't provide), and it would be very helpful to be able to see the full backtrace so I can debug more effectively.  I generally always want that anyway.

If this option is already provided and I've just missed it (which is possible), maybe some additional documentation would be helpful.

**Comment by wied03** [comment]
@bk2204 - I did some work on this with 0.5.0. Check out the beta using the browser formatter and see if that has improved this for you.

If you're curious, commits https://github.com/opal/opal-rspec/commit/f64587221b149af6a99728fbf8f9f2ff6dfa6454

**Comment by wied03** [comment]
Since I haven't heard anything on this, will go ahead and close. Feel free to comment if the 0.5 code isn't giving you what you're looking for.
