### ISSUE TITLE
Event Handlers still exists on spec completion

### ISSUE THREAD

**Issue by rpierreye** [opal/opal-rspec#16]
Testing methods that trigger events on Document, causes other specs (of other class) to fail. Maybe should clear DOM after every test?

I have to manually add an after block

```ruby
after do
  Document.off :event_name
end
```

**Comment by wied03** [comment]
@rpierreye - Other know much more about this than me, but could one argue that not all people using opal-rspec are working with the DOM, so DOM specific testing should have its state cleared manually, like how you are doing it?

**Comment by elia** [comment]
@rpierreye yes you need to treat it like you would do with a database (but without transactions) so you need to setup and clear manually. 

But if you come up with something better let us know as DOM specific support would make sense in the lib.
