### ISSUE TITLE
ability to change default spec directory

### ISSUE THREAD

**Issue by catmando** [opal/opal-rspec#23]
This is probably not worth fixing as there is a decent work around given [here](https://gist.github.com/catmando/d283739ef34e9368518c)

**Comment by ryanstout** [comment]
Actually, I'm not sure if there's a good way to handle it in opal-rspec or regular rspec, but I've got a similar problem where in volt I would love to put my spec directories inside of each component folder (so you could keep specs with the component). So if I can help here let me know.

**Comment by wied03** [comment]
I'm not sure it's a workaround. I think using the block could count as overriding the default. Not sure if that's really a problem.

**Comment by wied03** [comment]
Disregard my last comment, I think I underrated the verbosity of having to clear the existing paths (and add again) in the block

**Comment by elia** [comment]
@catmando I'd like to close this if you agree

**Comment by wied03** [comment]
@catmando @ryanstout - Might have some progress w/ https://github.com/opal/opal-rspec/pull/33, but @ryanstout I'm not sure it will support what you mention above but if you can craft a glob expression that matches what you want, this might work.

**Comment by wied03** [comment]
This will be taken care of with pattern support in the forthcoming 0.5 code

**Comment by wied03** [comment]
master, with a forthcoming 0.5 release (beta 3), supports supplying patterns
