### ISSUE TITLE
need to call autorun in last spec if using browser

### ISSUE THREAD

**Issue by catmando** [opal/opal-rspec#27]
says it all

You can't just put autorun into the spec helper as that will only work for the first file

seems to only be true if you are running in the browser

**Comment by elia** [comment]
The alternative is to manually call `Kernel.exit` which in turn would trigger `at_exit` block which is the trick used by rspec/autorun (also by minitest) if I understood the problem correctly…

**Comment by catmando** [comment]
None of this was needed in 0.7, it feels like a problem introduced in 0.8

**Comment by jgaskins** [comment]
Would an `Opal.Kernel.$exit()` call inside the rendered page somewhere after all the scripts are loaded work?

**Comment by catmando** [comment]
A call to Opal.Kernel.$exit() after everything is loaded would almost for sure work, but I still say this looks like some kind of regression introduced in 0.8

**Comment by jgaskins** [comment]
@catmando Certainly, I actually meant to direct that at @elia as a potential solution for `opal-rspec`, not to go into your app specs. :-)

**Comment by wied03** [comment]
@catmando, @jgaskins - I agree. This is more of an issue with opal-rails than opal-rspec I think. See discussion in https://github.com/opal/opal-rails/pull/67

**Comment by wied03** [comment]
I'll go ahead and close this due to the PR/issue in opal-rails referenced above.
