### ISSUE TITLE
RSpec 3.4 Support

### ISSUE THREAD

**Issue by wied03** [opal/opal-rspec#29]
Tasks:
- [x] - requires update
- [x] - sanity check fixes: core
- [x] - sanity check fixes: expectations
- [x] - sanity check fixes: matchers
- [x] - sanity check fixes: support
- [ ] - sanity check fixes: mocks
- [x] - other_specs run properly
  - [x] - browser
  - [x] - Rake
- [x] - With an intentional failure of other_specs:
  - [x] - browser run
  - [x] - Rake task run
- [x] - async basics
- [x] - git submodule update
- [ ] - opal_specs
  - [x] - Browser runs
  - [x] - memoization problem - fixed with `configure_example` workaround
  - [ ] - runs in Phantom without hanging - still hanging and missing 1 failure
  - [ ] - all pass
- [x] - rspec support
  - [x] - runs in Phantom without hanging
  - [x] - passes - only pending item was https://github.com/opal/opal/issues/1449, which stops `AllExceptionsExceptOnesWeMustNotRescue` case compare from working 
- [ ] - rspec core
  - [x] - compile
  - [x] - example run blocked by shared example/class issue - https://github.com/opal/opal/issues/1476
  - [x] - uninitialized constant `RSpec::Mocks::MarshalExtension::Marshal`
  - [x] - examples run
  - [ ] - correct ones pass - most example group specs pass, not getting success/fail counts with full suite. pure rspec run has 1,891 examples
- [ ] - rspec expectations (check rspec quantity)
- [ ] - rspec mocks (check rspec quantity)
- [ ] - Implement 'better_async' branch changes (might be easier to make around hooks work properly with async with 3.4). Need to understand why the 'result block' is actually happening though.
- [ ] - Verify which README limitations still apply
- [ ] - Require 0.10.2 in Gemspec (module inheritance bug)

**Comment by elia** [comment]
Yes please!

**Comment by elia** [comment]
But keep 0.8 as the target if possible

**Comment by wied03** [comment]
@elia - Do you want to have a branch for it now, or should I go ahead and do the development in my own fork and then do a PR?

**Comment by elia** [comment]
PR is fine

**Comment by elia** [comment]
missing stuff is now tracked by specs in master, organization is much better and reliable now, thanks to @iliabylich ✨
