### ISSUE TITLE
Investigate Using RSpec's Specs

### ISSUE THREAD

**Issue by wied03** [opal/opal-rspec#30]
Instead of the current Rake task setup, consider using RSpec's specs (and overriding the run_command approach they use). Then only the opal-rspec specific specs to maintain are the async ones.

**Comment by elia** [comment]
That would be awesome

**Comment by wied03** [comment]
@elia  - Started @ https://github.com/wied03/opal-rspec/tree/features/rspec_specs, based on the code @ https://github.com/opal/opal-rspec/pull/33. I think doing this first will make migrating to 3.2/3.3 easier since we'll know more about whether our foundation is solid.

**Comment by wied03** [comment]
@elia - Finally got the browser to at least run rspec-core's specs with several exclusions and patches. Thus far this has produced 1 fix and better documentation about what's not supported.

735 examples, 384 failures, 1 pending

Still more work to do, but it's a start

**Comment by wied03** [comment]
@elia - Making slow but steady progress on the rspec-core specs, which are probably much tougher than the expectations or mocks specs. The effort has already produced 2 fixes for Opal itself plus 2 issues in opal-rspec I didn't know about.

I think getting the rspec-core, expectations, and mocks specs running (with unsupportable items filtered) for version 0.5.0 is a good goal. What do you think?

**Comment by elia** [comment]
I think you're doing a tremendous job!

**Comment by wied03** [comment]
@elia - I'm down to 14 unexpected failures on the rspec-core specs and 265 (out of 1509 passing) for rspec-expectations specs.

Given the amount of time to get to that point (and what I would consider a big improvement over 0.4's setup), I think it's best to spend less time trying to fix everything and instead just get to a stopping point by documenting what works. By that I mean put tests that really ought to pass in a filter/bugs/** file and then put what we know doesn't work in the README. Then this can get released (as 0.5) and people can benefit from the improvements that have already been made while the remaining pieces are whittled away.

Sound good?

**Comment by wied03** [comment]
I went ahead with that approach, but I did try and fix issues when I could. Now the core, support, and expectation specs all "pass" with some exclusions. Working on the mock specs now.

**Comment by elia** [comment]
w00t!

**Comment by wied03** [comment]
Right now mocks is a pain because any_instance_of wipes out the entire Example class. More generally though, if nothing else, we'll now have a much better idea (and I've been updating the README) about what works and what doesn't. Plus rspec uses so many aspects of the Ruby language that it caused all of these PRs I've been submitting to be teased out.

**Comment by wied03** [comment]
Investigation is over, it's done :)

**Comment by elia** [comment]
:tophat:
