### ISSUE TITLE
bundle exec rake build doesn't create rspec.js

### ISSUE THREAD

**Issue by suchipi** [opal/opal-rspec#35]
It only builds the gem...

**Comment by elia** [comment]
Good catch, it's the readme that needs updating as the rspec.js step is no longer needed. Would probably make sense to add a `dist` task for building opal-rspec.js

**Comment by suchipi** [comment]
Having a dist task would be very useful, without one it seems opal-rspec can only be used when building via MRI

**Comment by wied03** [comment]
@elia - I've done a lot of README updates with the rspec branch

**Comment by wied03** [comment]
@suchipi - Is this a common use case? I would imagine most people would use opal-rspec as a GEM to test and would not "ship" their compiled opal code with their application.

**Comment by suchipi** [comment]
I ran into it while using https://github.com/mikamai/meteor-opal/ to use Opal in a JavaScript framework. All the compilation is done in JS, there is no MRI world with this setup.

**Comment by elia** [comment]
After adding the `dist` task we'll make sure it's published on the CDN (cdn.opalrb.org)

cc @mogztter

**Comment by wied03** [comment]
Added dist task with commit https://github.com/opal/opal-rspec/commit/333068cce66fc6b4d452f553e970f5d3f026f905
