### ISSUE TITLE
Enable diff support with diff-lcs

### ISSUE THREAD

**Issue by wied03** [opal/opal-rspec#39]
Would need to get https://github.com/halostatue/diff-lcs working on Opal, then tie that in

**Comment by iliabylich** [comment]
@wied03 Is still an issue? Got the whole gem compiled with https://github.com/opal/opal/pull/1497. Example from diff-lcs' README works as expected.

**Comment by wied03** [comment]
@iliabylich - Yep still an issue, although this is an enhancement being tracked for opal-rspec. I have never tried to use diff-lcs.
