### ISSUE TITLE
Add executable and reconfigure Rake Task to use it

### ISSUE THREAD

**Issue by wied03** [opal/opal-rspec#45]
Work more like RSpec does where the Rake task calls the executable

**Comment by wied03** [comment]
Sort of related to https://github.com/opal/opal-rspec/issues/41

**Comment by hmdne** [comment]
While we don't call the RSpec binary in Opal-RSpec 1.1.0, the code of the executable, the rake task and the runner class have been mostly unified. Also ,we actually run Opal in a separate process.
