### ISSUE TITLE
Travis errors out with CRuby v1.9.3

### ISSUE THREAD

**Issue by elia** [opal/opal-rspec#48]
It errors because of a too new version of rack that only supports 
Ruby >= 2.0.m, it's probably just 
a matter of tweaking the test stuff that's present in the Gemfile. 

I disabled 1.9.3 in https://github.com/opal/opal-rspec/commit/bb666f329c227479f90ebf64fee453911a6de9dd but should be fixed and re-enabled soon.

**Comment by wied03** [comment]
Should we keep supporting 1.9.3 ?

**Comment by elia** [comment]
That's something I was wondering too, but I in the end considering it's [usage][1] and the fact that it's supported in the main opal repo I think the answer is yes. 

[1]: https://semaphoreci.com/blog/2015/12/01/ruby-version-usage-in-commercial-projects-2015-edition.html?utm_source=rubyweekly&utm_medium=email

**Comment by wied03** [comment]
Added a special case in the Gemfile and travis config, now 1.9.3 is behaving like the other sub-builds
