### ISSUE TITLE
Async specs shortcomings

### ISSUE THREAD

**Issue by meh** [opal/opal-rspec#5]
Async specs need some fixing, a common error sprouting up is [this](https://travis-ci.org/opal/opal-browser/jobs/17740198).

It obviously doesn't make any sense, so it's either coming from something using `run_async` out of context, or dunno.

There's to consider I named both methods `async`, I assumed `AsyncDefinitions` and `AsyncHelpers` were never going to collide. Is this really the case?

Other than that the formatting of async specs needs some fixing, especially regarding where/how it's formatted.

Right now it just gets mixed in with other example groups, and it's really misleading.

**Comment by wied03** [comment]
@meh - another thing i've noticed is that the reporter summary totals don't include failed async tests and the exit status of the text formatter/rake task doesn't include a failure if these fail. Maybe we could refactor these to use a Jasmine like approach, which uses a done object passed to the async block and the runner can asynchronously wait (check in periodically for the done call)? On a related note, the AsyncRunner class doesn't seem to be fully used to actually run the specs either. I removed it from the code and the specs all passed (just the summary broke).

**Comment by wied03** [comment]
Actually, re: the last sentence on my last comment, the only reason the summary broke was because when I yanked out the AsyncRunner, I took this block with it:
```
run_async_examples do
   self.finish
end
```
It appears the AsyncRunner was not doing anything.

**Comment by wied03** [comment]
See #17

**Comment by wied03** [comment]
@adambeynon @meh  - I think this can also be closed since master has refactored this.
