### ISSUE TITLE
filter_run_excluding not working?

### ISSUE THREAD

**Issue by catmando** [opal/opal-rspec#61]
```ruby
 RSpec.configure do |config|
    config.include React::SpecHelpers
    config.filter_run_excluding :ruby => true
  end
``` 
seems to have no effect

If you clone this repo: https://github.com/catprintlabs/reactor-router/tree/filter-excluding-demo

and run `bundle exec rake`

you will see the problem... there is only one spec, consisting of one rspec and one opal-rspec test which should run mutually exclusively....

**Comment by wied03** [comment]
@catmando - quick close?
