### ISSUE TITLE
stub_const doesn't work quite the same in opal 0.9

### ISSUE THREAD

**Issue by catmando** [opal/opal-rspec#63]
I am not 100% sure this is an opal-rspec, opal issue, or even an issue, but it used to work in Opal 0.8, but now in Opal 0.9 with latest rspec it fails:

``` ruby
  it "can add class names by the haml .class notation" do
    stub_const 'TestMod123::Bar', Class.new(React::Component::Base)
    TestMod123::Bar.class_eval do
      collect_other_params_as :attributes
      def render
        "a man walks into a bar".span(attributes)
      end
    end
    stub_const 'Foo', Class.new(React::Component::Base)
    Foo.class_eval do
      def render
        TestMod123::Bar().the_class
      end
    end

    expect(React.render_to_static_markup(React.create_element(Foo))).to eq('<span class="the-class">a man walks into a bar</span>')
  end
```

The problem is that React::Component::Base wants to find its parent name if it is defined, so that the method "Bar()" can be defined in the parent module (TestMod123).   putting some traces in the code shows that in 0.9 with latest opal-rspec, React::Component.included is being called BEFORE the name of the class is set.  It does get set, but only after the class is created.

**Comment by wied03** [comment]
`stub_const` has always had lingering issues. I've never been a fan of it in my tests though so it hasn't been a problem for me. Frankly, I can't imagine it becoming much of a priority as long as Opal's underlying constant issue is there.

If I get some time I'll try and see what's going on. Most of my energy right now though has to go towards getting RSpec 3.4 working.

**Comment by catmando** [comment]
no big deal but do you have any recommendation for fixing that spec?  What I am doing now is to just declare TestMod123::Bar outside the spec, and let it sit there...  These test structures go back to @zetachang, so perhaps there is a better way?

**Comment by wied03** [comment]
Any reason they have to be assigned a constant? Why not do it like this?

```ruby
  it "can add class names by the haml .class notation" do
    mod123 = Class.new(React::Component::Base) do
      collect_other_params_as :attributes
      def render
        "a man walks into a bar".span(attributes)
      end
    end
    foo = Class.new(React::Component::Base) do
      def render
        mod123().the_class
      end
    end

    expect(React.render_to_static_markup(React.create_element(foo))).to eq('<span class="the-class">a man walks into a bar</span>')
  end
```

**Comment by catmando** [comment]
Most cases yes, but specifically I need to test that TestMod123::Bar works... so I need at least one test that I do assign to a constant...

**Comment by wied03** [comment]
Why though? Is this to test the React display name stuff?

**Comment by catmando** [comment]
No because in the dsl you can do this:

def render
    TestMod123::Bar()
end

**Comment by wied03** [comment]
OK I see. You're testing the equivalent of this: http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-String

**Comment by wied03** [comment]
I think doing this with any type of anonymous class will be difficult. Even in MRI, `included` doesn't know the name of the class yet. Getting opal and opal-rspec to do something different could be quite tricky and probably not desirable.

code:
```ruby
module Foo
  def self.included(base)
    puts "we are #{base}"
  end
end

class Bar
  include Foo
end

Toodles = Class.new do
  include Foo
end
```

MRI output:
```
we are Bar
we are #<Class:0x007fc08b886a78>
```

I think even with vanilla RSpec on MRI, you wouldn't get this to work without hacking/calling included again, etc.

I think creating a normal fixture class outside of the test might be your best option. Might want to make the behavior fail gracefully in case someone wants to use an anonymous class for a React component.

**Comment by elia** [comment]
missing/broken features are now tracked by spec filters on master
