### ISSUE TITLE
Support random order

### ISSUE THREAD

**Issue by brodock** [opal/opal-rspec#66]
https://github.com/opal/opal/issues/639 is closed as https://github.com/opal/opal/pull/1540 got merged, so we can check for specific Opal version and disable the workaround.

What are your thoughts?

**Comment by wied03** [comment]
Sounds like something I'd like to do with the RSpec 3.4 branch of opal-rspec that I've been working on. The only question is time.

**Comment by elia** [comment]
missing features from the original RSpec are now tracked by the upstream specs we run

We'll get around fixing random order, eventually
