### ISSUE TITLE
Trying to run phantomjs or in-browser tests throws Sprockets::FileNotFound

### ISSUE THREAD

**Issue by jeremyjaybaker** [opal/opal-rspec#69]
I have a feeling this is just a configuration issue since I'm not very familiar with Sprockets. I've tried following the instructions at https://github.com/opal/opal-rspec#run-specs-in-a-browser and at https://github.com/opal/opal-rspec#run-specs-in-phantomjs and I get the following error both times: 

`Sprockets::FileNotFound at /
couldn't find file 'config/environment' with type 'application/javascript' Checked in these paths: /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-0.10.3/opal /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-0.10.3/stdlib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-0.10.3/lib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-jquery-0.4.2/lib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-activesupport-0.3.0/opal /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-rspec-0.6.0/opal /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-rspec-0.6.0/rspec/lib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-rspec-0.6.0/rspec-core/lib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-rspec-0.6.0/rspec-expectations/lib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-rspec-0.6.0/rspec-mocks/lib /home/jeremy/.rvm/gems/ruby-2.3.1/gems/opal-rspec-0.6.0/rspec-support/lib /home/jeremy/Documents/repos/CASinoApp/spec`

**Comment by wied03** [comment]
I haven't had much time to work on opal-rspec but maybe this week I can
shift gears and take a look at this.

sent from my mobile device

**Comment by jeremyjaybaker** [comment]
Thanks! Let me know what parts of my config you need to see. My Gemfile and application.rb might be helpful?

**Comment by elia** [comment]
I just released v0.6.2 for opal 0.10.x and sprckets seemed to work fine, in case it's still relevant 😅.
I'll close this one, but happy to help in case it's needed.
