### ISSUE TITLE
uninitialized constant OPAL_PLATFORM

### ISSUE THREAD

**Issue by anharu2394** [opal/opal-rspec#78]
opal (~> 0.11.0)
opal-rspec (0.7.0.rc.2)

I try to run specs in browser.
when run `bundle exec rackup` command,the error occurs.
![image](https://user-images.githubusercontent.com/26423094/47913089-233b6080-dede-11e8-83c0-90edb41b0de3.png)

`config.ru`
```ruby
require 'bundler'
Bundler.require
require 'opal/rspec'
sprockets_env = Opal::RSpec::SprocketsEnvironment.new(spec_pattern='spec/opal/*_spec.{rb,opal}')
run Opal::Sprockets::Server.new(sprockets: sprockets_env) { |s|
  s.main = 'opal/rspec/sprockets_runner'
	s.append_path 'spec/opal'
  sprockets_env.add_spec_paths_to_sprockets
  s.debug = false
}
```

**Comment by anharu2394** [comment]
tha same error occurs again.
![image](https://user-images.githubusercontent.com/26423094/48066134-1f764980-e210-11e8-9ec0-4fce9a54c8f4.png)

My `spec_helper.rb`
```
require "bundler/setup"
require "rubelm"
require "opal-browser"
require 'opal/platform'

RSpec.configure do |config|
  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end
end

```

**Comment by anharu2394** [comment]
How is the problem solved?

**Comment by elia** [comment]
Ok, found a temporary solution

add `spec/opal/custom_sprockets_runner.rb` with this content:

```rb
require 'opal'
require 'opal/platform'
require 'opal/rspec/sprockets_runner'
```

then replace the main file in `config.ru` with `opal/custom_sprockets_runner.rb`


---

meanwhile I'll fix it on master, let me know how it goes 👍

**Comment by anharu2394** [comment]
My `config.ru`
```ruby
require 'bundler'
Bundler.require
require 'opal/rspec'
sprockets_env = Opal::RSpec::SprocketsEnvironment.new(spec_pattern='spec/opal/*_spec.{rb,opal}')
run Opal::Sprockets::Server.new(sprockets: sprockets_env) { |s|
  s.main = 'opal/custom_sprockets_runner.rb'
	s.append_path 'spec/opal'
  sprockets_env.add_spec_paths_to_sprockets
  s.debug = false
}

```
My `spec/opal/custom_sprockets_runner.rb`
```ruby
require 'opal'
require 'opal/platform'
require 'opal/rspec/sprockets_runner'

```
But running `bundle exec rackup`,the error occured.
`RuntimeError: Cannot find asset: opal/custom_sprockets_runner.rb`
![image](https://user-images.githubusercontent.com/26423094/48197421-0a78f200-e399-11e8-9229-bfcaaca01d56.png)

**Comment by elia** [comment]
yeah sorry, I got the path wrong 😄

Anyway I pushed the fix to master, you should be able to use the original code by pointing to the github gem in your Gemfile:

```rb
gem 'opal-rspec', git: 'https://github.com/opal/opal-rspec', submodules: true
```
