### ISSUE TITLE
Headless Chrome support

### ISSUE THREAD

**Issue by youchan** [opal/opal-rspec#80]
PhantomJS was ended and Opal is supporting headless chrome. => https://github.com/opal/opal/blob/master/lib/opal/cli_runners/chrome.rb
opal-rspec should support headless chrome and remove PhantomJS support.

**Comment by elia** [comment]
@youchan absolutely agree, that has been delayed to give priority to Opal 0.11 compatibility but it's something that should be done 👍

**Comment by hmdne** [comment]
Already done in Opal cli_runners a long time ago. This issue can be closed.

**Comment by elia** [comment]
Thanks for pointing that out @hmdne, closing 👍
